version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"   # API
      - "9229:9229"   # Debugger
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=mydb
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydb?schema=public  # Prisma
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      # - /app/node_modules
    depends_on:
      - db
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate dev --name init --skip-seed &&
        node --inspect=0.0.0.0:9229 server.js
      "

  frontend:
    build: ./frontend # React app
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevents node_modules overwrite
    depends_on:
      - backend

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      # - ./backend/db/db.sql:/docker-entrypoint-initdb.d/db.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
